FROM yusun9/wham-vitpose-dpvo-cuda11.3-python3.9:latest

# RUN pip install --no-cache-dir gdown 
RUN pip install --no-cache-dir pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1110/download.html

WORKDIR /code
COPY . /code

ENV PYTHONUNBUFFERED=1
ENV CUDA_VISIBLE_DEVICES=""
ENV OMP_NUM_THREADS=1
ENV MKL_NUM_THREADS=1
ENV OPENBLAS_NUM_THREADS=1
ENV NUMEXPR_NUM_THREADS=1
ENV VECLIB_MAXIMUM_THREADS=1
ENV KMP_AFFINITY=disabled
ENV KMP_INIT_AT_FORK=FALSE
ENV MPLBACKEND=Agg
ENV PYTHONFAULTHANDLER=1
