FROM runpod/pytorch:2.2.0-py3.10-cuda12.1.1-devel-ubuntu22.04

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
COPY ./third-party/ViTPose/requirements/runtime.txt /code/third-party/ViTPose/requirements/runtime.txt
COPY ./services/wham_api_service/requirements.txt /code/services/wham_api_service/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r third-party/ViTPose/requirements/runtime.txt
RUN pip install --no-cache-dir -r services/wham_api_service/requirements.txt

RUN pip install https://github.com/MiroPsota/torch_packages_builder/releases/download/pytorch3d-0.7.8/pytorch3d-0.7.8%2Bpt2.2.0cu121-cp310-cp310-linux_x86_64.whl

COPY . /code

ENV PYTHONUNBUFFERED=1
ENV CUDA_VISIBLE_DEVICES=""
ENV OMP_NUM_THREADS=1
ENV MKL_NUM_THREADS=1
ENV OPENBLAS_NUM_THREADS=1
ENV NUMEXPR_NUM_THREADS=1
ENV VECLIB_MAXIMUM_THREADS=1
ENV KMP_AFFINITY=disabled
ENV KMP_INIT_AT_FORK=FALSE
ENV MPLBACKEND=Agg
ENV PYTHONFAULTHANDLER=1

WORKDIR /code/services/wham_api_service

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]