"""
Run WHAM 3D pose inference using pre-existing 2D preprocessing artifacts.

This script assumes tracking_results.pth and slam_results.pth already exist
in the output directory (generated by extract_2d_poses.py or similar).

Does NOT run 2D detection or SLAM—only WHAM 3D body pose inference.

Usage:
    python extract_3d_poses.py \\
        --video path/to/video.mp4 \\
        --output_dir output/path \\
        [--visualize] [--save_pkl] [--run_smplify] \\
        [--device cuda:0] [--estimate_local_only] [--calib calib.txt]
"""
import argparse
import os
import os.path as osp
from collections import defaultdict
from pathlib import Path

import cv2
import joblib
import numpy as np
import torch

# WHAM imports
from configs.config import get_cfg_defaults
from lib.data.datasets import CustomDataset
from lib.models import build_network, build_body_model
from lib.models.smplify import TemporalSMPLify
from lib.utils.transforms import matrix_to_axis_angle


def main():
    ap = argparse.ArgumentParser(
        description="Run WHAM 3D pose inference on preprocessed 2D detection data"
    )
    ap.add_argument("--video", required=True, type=str, help="Path to input video")
    ap.add_argument(
        "--output_dir", required=True, type=str, help="Output directory with preprocessing artifacts"
    )
    ap.add_argument(
        "--device", default="cuda:0", type=str, help="Device for model inference (cuda:0, cpu, etc.)"
    )
    ap.add_argument(
        "--estimate_local_only",
        action="store_true",
        help="Force local-only estimation (ignores slam_results.pth)",
    )
    ap.add_argument(
        "--visualize", action="store_true", help="Visualize output mesh"
    )
    ap.add_argument(
        "--save_pkl", action="store_true", help="Save output as wham_output.pkl"
    )
    ap.add_argument(
        "--run_smplify", action="store_true", help="Run Temporal SMPLify for post processing"
    )
    ap.add_argument(
        "--calib", default=None, type=str, help="Optional calibration file path"
    )
    args = ap.parse_args()

    cfg = get_cfg_defaults()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Verify input video exists
    if not osp.exists(args.video):
        raise RuntimeError(f"Video not found: {args.video}")

    # Verify preprocessing artifacts exist
    tracking_pth = output_dir / "tracking_results.pth"
    slam_pth = output_dir / "slam_results.pth"
    if not tracking_pth.is_file():
        raise RuntimeError(
            f"tracking_results.pth not found in {output_dir}: run extract_2d_poses.py first"
        )
    if not slam_pth.is_file():
        raise RuntimeError(
            f"slam_results.pth not found in {output_dir}: run extract_2d_poses.py first"
        )

    # Load video metadata
    cap = cv2.VideoCapture(args.video)
    if not cap.isOpened():
        raise RuntimeError(f"Cannot open video: {args.video}")
    fps = cap.get(cv2.CAP_PROP_FPS) or 30.0
    length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    cap.release()

    print(f"[extract_3d_poses] Video: {args.video}")
    print(f"[extract_3d_poses] FPS: {fps}, Length: {length} frames, Resolution: {width}x{height}")
    print(f"[extract_3d_poses] Device: {args.device}")
    print(f"[extract_3d_poses] Output: {output_dir}/wham_output.pkl")
    print(f"[extract_3d_poses] estimate_local_only: {args.estimate_local_only}")

    # Load preprocessing artifacts
    print(f"[extract_3d_poses] Loading preprocessing artifacts...")
    tracking_results = joblib.load(str(tracking_pth))
    slam_results = joblib.load(str(slam_pth))

    # Build WHAM network
    print(f"[extract_3d_poses] Building WHAM network...")
    smpl_batch_size = cfg.TRAIN.BATCH_SIZE * cfg.DATASET.SEQLEN
    smpl = build_body_model(args.device, smpl_batch_size)
    network = build_network(cfg, smpl)
    network.eval()

    # Run WHAM inference
    print(f"[extract_3d_poses] Running WHAM inference...")
    results = defaultdict(dict)

    with torch.no_grad():
        # Build dataset from preprocessing artifacts
        dataset = CustomDataset(cfg, tracking_results, slam_results, width, height, fps)

        n_subjs = len(dataset)
        for subj in range(n_subjs):
            if cfg.FLIP_EVAL:
                # Forward pass with flipped input
                flipped_batch = dataset.load_data(subj, True)
                _id, x, inits, features, mask, init_root, cam_angvel, frame_id, kwargs = flipped_batch
                flipped_pred = network(
                    x, inits, features, mask=mask, init_root=init_root,
                    cam_angvel=cam_angvel, return_y_up=True, **kwargs
                )

                # Forward pass with normal input
                batch = dataset.load_data(subj)
                _id, x, inits, features, mask, init_root, cam_angvel, frame_id, kwargs = batch
                pred = network(
                    x, inits, features, mask=mask, init_root=init_root,
                    cam_angvel=cam_angvel, return_y_up=True, **kwargs
                )

                # Merge two predictions
                from lib.utils.imutils import avg_preds
                flipped_pose, flipped_shape = flipped_pred['pose'].squeeze(0), flipped_pred['betas'].squeeze(0)
                pose, shape = pred['pose'].squeeze(0), pred['betas'].squeeze(0)
                flipped_pose, pose = flipped_pose.reshape(-1, 24, 6), pose.reshape(-1, 24, 6)
                avg_pose, avg_shape = avg_preds(pose, shape, flipped_pose, flipped_shape)
                avg_pose = avg_pose.reshape(-1, 144)
                avg_contact = (flipped_pred['contact'][..., [2, 3, 0, 1]] + pred['contact']) / 2

                # Refine trajectory with merged prediction
                network.pred_pose = avg_pose.view_as(network.pred_pose)
                network.pred_shape = avg_shape.view_as(network.pred_shape)
                network.pred_contact = avg_contact.view_as(network.pred_contact)
                output = network.forward_smpl(**kwargs)
                pred = network.refine_trajectory(output, cam_angvel, return_y_up=True)
            else:
                # Single pass inference
                batch = dataset.load_data(subj)
                _id, x, inits, features, mask, init_root, cam_angvel, frame_id, kwargs = batch
                pred = network(
                    x, inits, features, mask=mask, init_root=init_root,
                    cam_angvel=cam_angvel, return_y_up=True, **kwargs
                )

            # Optional SMPLify refinement
            if args.run_smplify:
                smplify = TemporalSMPLify(smpl, img_w=width, img_h=height, device=args.device)
                input_keypoints = dataset.tracking_results[_id]['keypoints']
                pred = smplify.fit(pred, input_keypoints, **kwargs)

                with torch.no_grad():
                    network.pred_pose = pred['pose']
                    network.pred_shape = pred['betas']
                    network.pred_cam = pred['cam']
                    output = network.forward_smpl(**kwargs)
                    pred = network.refine_trajectory(output, cam_angvel, return_y_up=True)

            # Store results
            pred_body_pose = matrix_to_axis_angle(pred['poses_body']).cpu().numpy().reshape(-1, 69)
            pred_root = matrix_to_axis_angle(pred['poses_root_cam']).cpu().numpy().reshape(-1, 3)
            pred_root_world = matrix_to_axis_angle(pred['poses_root_world']).cpu().numpy().reshape(-1, 3)
            pred_pose = np.concatenate((pred_root, pred_body_pose), axis=-1)
            pred_pose_world = np.concatenate((pred_root_world, pred_body_pose), axis=-1)
            pred_trans = (pred['trans_cam'] - network.output.offset).cpu().numpy()

            results[_id]['pose'] = pred_pose
            results[_id]['trans'] = pred_trans
            results[_id]['pose_world'] = pred_pose_world
            results[_id]['trans_world'] = pred['trans_world'].cpu().squeeze(0).numpy()
            results[_id]['betas'] = pred['betas'].cpu().squeeze(0).numpy()
            results[_id]['verts'] = (pred['verts_cam'] + pred['trans_cam'].unsqueeze(1)).cpu().numpy()
            results[_id]['frame_ids'] = frame_id

    # Save results
    if args.save_pkl:
        out_path = osp.join(str(output_dir), "wham_output.pkl")
        joblib.dump(results, out_path)
        print(f"[extract_3d_poses] Saved: {out_path}")

    # Visualize
    if args.visualize:
        from lib.vis.run_vis import run_vis_on_demo
        with torch.no_grad():
            run_vis_on_demo(
                cfg, args.video, results, str(output_dir), network.smpl,
                vis_global=not args.estimate_local_only
            )

    print(f"[extract_3d_poses] Success")


if __name__ == "__main__":
    main()
